---
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch git tag info
        run: git fetch --tags --force
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install Arduino CLI host dependencies
        run: sudo apt install -y python-is-python3
      - name: Install Arduino CLI python dependencies
        run: pip3 install pyserial
      - name: Setup Arduino CLI environment
        run: make env
      - name: Build the sketch
        run: make API_SECRET_SALT="${{ secrets.API_SECRET_SALT }}"
      - name: Download external flashing tools to attach to release
        run: curl -o esptool-2.6.1-windows.zip https://dl.espressif.com/dl/esptool-2.6.1-windows.zip && unzip esptool-2.6.1-windows.zip
      - name: Grab core version
        run: echo "CORE_VERSION=$(make print-core-version)" >> $GITHUB_ENV
      - name: Zip artifacts
        run: >
          zip --junk-paths msp-firmware-${{ env.RELEASE_VERSION }}.zip \
            README.md \
            scripts/RUNME.BAT \
            var/build/msp-firmware.ino.bin \
            var/build/msp-firmware.ino.partitions.bin \
            var/packages/esp32/hardware/esp32/${{ env.CORE_VERSION }}/tools/partitions/boot_app0.bin \
            var/packages/esp32/hardware/esp32/${{ env.CORE_VERSION }}/tools/sdk/bin/bootloader_qio_80m.bin \
            esptool/esptool.exe
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: msp-firmware-${{ env.RELEASE_VERSION }}.zip
          asset_name: msp-firmware-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
